{% set name = "Jug" %}
{% set version = "2.2.0" %}
{% set sha256 = "d98f7146be43c95f54a86ead8aaf6b6044f667b2da3d77f3c1828a1b0477392b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - jug = jug.jug:main

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - six
    - bottle
    - pyyaml

test:
  imports:
    - jug
  commands:
    - jug -h

about:
  home: https://github.com/luispedro/jug
  license: MIT
  license_family: MIT
  license_file: COPYING.MIT
  summary: Task based Python workflow system

  # The remaining entries in this section are optional, but recommended
  description: |
    Jug allows you to write code that is broken up into
    tasks and run different tasks on different processors.
  doc_url: https://jug.readthedocs.io/
  dev_url: https://github.com/luispedro/jug
  identifiers:
    - doi: 10.5334/jors.161

extra:
  recipe-maintainers:
    - luispedro
