{% set name = "Jug" %}
{% set version = "2.3.1" %}
{% set sha256 = "6364d6a898bb1a3996505a5ed5bd79d0d830470f552a10a4e44a0de4d0dc3d75" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - jug = jug.jug:main

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - bottle
    - pyyaml

test:
  imports:
    - jug
  commands:
    - jug -h

about:
  home: https://github.com/luispedro/jug
  license: MIT
  license_family: MIT
  license_file: COPYING.MIT
  summary: Task based Python workflow system

  description: |
    Jug allows you to write code that is broken up into
    tasks and run different tasks on different processors.
  doc_url: https://jug.readthedocs.io/
  dev_url: https://github.com/luispedro/jug
  identifiers:
    - doi: 10.5334/jors.161

extra:
  recipe-maintainers:
    - luispedro
