{% set name = "Jug" %}
{% set version = "1.6.8" %}
{% set sha256 = "5790c699c04b874dcad5439e0278bc0d5a9bd0c9f889119412b11a9d2c0d3468" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - jug = jug.jug:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - six
    - bottle
    - pyyaml

test:
  imports:
    - jug
  commands:
    - jug -h

about:
  home: http://github.com/luispedro/jug
  license: MIT
  license_family: MIT
  license_file: COPYING.MIT
  summary: 'Task based Python workflow system'

  # The remaining entries in this section are optional, but recommended
  description: |
    Jug allows you to write code that is broken up into
    tasks and run different tasks on different processors.
  doc_url: https://jugreadthedocs.io/
  dev_url: https://github.com/luispedro/jug

extra:
  recipe-maintainers:
    - luispedro
