travis:
  secure:
    BINSTAR_TOKEN: o+y2fWHRKFLJU5YN5dKIP9YO9cj/n7gF7b1VFtRYUdufGPicRtP4qmvjPDAOZLhrOF8Du8YPdSQE7LLmehbHPlJyMJDrcgKhwQkVk/Asp1JbtqMgmzgyKyeao1Ql7vdxQ0hy0aNYxfMvvx2dwxX7ynsohoV7hxpn1x7rr1YS2IsYR4L4W2vkKkMlkqXtZXETWjDP/YKT7c4lczvdRTLc3iB6ftzEzfZIdVTiVXRt+P1BnArU76rH5LUPwR1DMy5CPHa0bmvYeIBKpTXjKaSgEmU3Iut+3Pj4j0fsGuRlmHmqIFrM5n4StuKSrwiBvMAPWCCIdyfqhweZfOLeMGU1gHyxjBsNU+i0VA8rhlunuYKqD7yt3ivK2pYgMlq8OgZCBm+uETRvASGWjSGI+nJP7xOvRAC/3DIX7otu8YbTgsydb3YVX1/L5FR1CejdMnSFjNo1eL+PqjVBxB9U1feR8QuAXRVE+JuJciHlbVcn2dU3UGlmerk7+a8m/vL5aSlI5eCJCAm+4LhMvU/1e0wL9ouRCxF3/p3wj/KgmyrrqdPwigl5wBrw2zwHlQ41TUVo4CwIybjpURIq9ujOuvfabCJapNzLotE9X/Z0oeBP7jzE+oqHynk2cxdZawzfWfigkG/hG9VmHVf0NLD1bWaev7As/9JjWorHMnTC5z39MTA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
