travis:
  secure:
    BINSTAR_TOKEN: fWXCtQJdz78Jpv4hT9ZBRCGkvTXTR3QzyW8DznbDQZredu6hHGhya9i2mwL5UQ2LZR2OqjhcX6DnNLGp6i69vdo6BDGriD2Ks6g0tAoXWbrd5GHIGRh75CuDLb7TW8rJW06z5BfxcG4ZpIa09l5xnN00wzHFJJaGMcAd2VPL7zh+MPesYlzP6Vn2dyzzxcQ6HhXCHp6rJHAc+CbKGpOmT5sPv5qn07TqppKCH5R23YPzmQP+ai4Q7/DxUfLc/wwBLogUZhAeBWPViYCQZUUY4tI9Z2MQGdAioi0jQJeQzrXRO7cmg7zBku6n02nyMU4ibuYUtAxM5E6tduRXSDr84dQm7DqI+FJBZ3HaLzKpXwME2VzWDDpH6TuQ5oxjH5mRPOM1nrBC/6qKnwNdZ9AHEPKgZKt0PKb/ABrGev5TJBtY1vV9twWgQ/f0vZqhLOm28C7uDl7dXrSIYCejztpDDvL+NbTeMAe6Un5pKChSSCenNvtVkRe3LQt1HEfrlZa29nvQqYWe9oP4Qm8eSs7+k9zU0sBxcBjC6DaKzd6JkLoELN6iokUJ0wWGqxF+FS3p/YHDkw5yoLX+8Nt2J7ejbUyOF7HnUfByK4HaVltq/+GDUqO0spL++BKHi156fQMXFrgQ+i8PZCqSX8FKq0VbgirRHecPHGNHudZDmNJj+88=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
